autofor/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('list.urls')),
    url(r'^', include('analysis.urls')),
    url(r'^', include('disk.urls')),
    url(r'^', include('network.urls')),
    url(r'^', include('manager.urls')),
    
]+ static(settings.MEMORY_IMG_URL, document_root = settings.MEMORY_IMG_PATH) + static(settings.FILE_URL, document_root = settings.FILE_PATH)

disk/urls.py
from django.conf.urls import url
from . import views

app_name = 'disk'

urlpatterns = [
    url(r'^analysis/disk/$', views.disk, name='disk'),
    url(r'^analysis/disk/dumped/$', views.dumped_files, name='dumped_files'),
    url(r'^analysis/disk/deleted/$', views.deleted_files, name='deleted_files'),

]

list/urls.py
from django.conf.urls import url
from . import views

app_name = 'list'

urlpatterns = [
    url(r'^list$', views.list, name='list'),
    url(r'^list/ready/(?P<id>[0-9]+)/$', views.ready, name='ready'),
    url(r'^list/add$', views.add_case, name='add_case'),
    url(r'^list/delete/(?P<id>[0-9]+)/$', views.delete_case, name='delete_case'),
    url(r'^$', views.login_user, name='login_user'),
    url(r'^logout$', views.logout_user, name='logout_user'),
]

manager/urls.py
from django.conf.urls import url
from . import views

app_name = 'manager'

urlpatterns = [
    url(r'^manager/$', views.index, name='index'),
    url(r'^manager/users/$', views.users, name='users'),
    url(r'^manager/users/add$', views.user_add, name='user_add'),
    url(r'^manager/users/remove/(?P<user>[a-zA-Z]+)/$', views.user_remove, name='user_remove'),
    url(r'^manager/users/change/(?P<user>[a-zA-Z]+)/$', views.user_ch, name='user_ch'),
    url(r'^manager/users/change/gen/(?P<user>[a-zA-Z]+)/$', views.user_ch_gen, name='user_ch_gen'),
    url(r'^manager/users/change/pwd/(?P<user>[a-zA-Z]+)/$', views.user_ch_pwd, name='user_ch_pwd'),
    url(r'^manager/users/$', views.groups, name='groups'),
    url(r'^manager/groups/change/(?P<grp>[a-zA-Z]+)/$', views.group_ch, name='group_ch'),
    url(r'^manager/clears/$', views.clears, name='clears'),
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import *
from list.models import Case
import os
from django.contrib import admin
from django.contrib.admin.models import LogEntry


def index(request):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	if not request.user.is_superuser:
		return redirect('list:login_user')
	case_n = Case.objects.count()
	user_n = User.objects.count()
	disk_usage = os.popen('du -hc . | tail -1 |tr "\t" " "|cut -d " " -f1').read
	print("_______")
	log = LogEntry.objects.all()
	log_table = []
	action_flag = 'Added'
	for l in log:
		if str(l.action_flag) == '1':
			action_flag = 'Added'
		if str(l.action_flag)== '2':
			action_flag = 'Changed'
		if str(l.action_flag)== '3':
			action_flag = 'Deleted'
		log_table.append([str(l.user), action_flag, str(l.object_repr), str(l.action_time)])
	return render(request, 'manager/index.html', {'case_n':case_n,'user_n':user_n,'disk_usage':disk_usage,'logs':log_table})


def users(request):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	if not request.user.is_superuser:
		return redirect('list:login_user')
	users = User.objects.all()
	return render(request, 'manager/users.html', {'users':users})


def user_add(request):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	if not request.user.is_superuser:
		return redirect('list:login_user')
	##add the user
	if request.method == 'POST':
		User.objects.create_user(username=request.POST['username'].replace(" ", "_"), email=request.POST['email'], first_name=request.POST['first_name'], last_name=request.POST['last_name'], password=request.POST['password'])
	return redirect('manager:users')


def user_remove(request, user):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	if not request.user.is_superuser:
		return redirect('list:login_user')
	##remove the user
	u = User.objects.get(username=user)
	u.delete()
	return redirect('manager:users')


def user_ch(request, user):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	if not request.user.is_superuser:
		return redirect('list:login_user')
	cuser = User.objects.get(username=user)
	return render(request, 'manager/user_ch.html', {'user':cuser})


def user_ch_gen(request, user):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	if not request.user.is_superuser:
		return redirect('list:login_user')
	##change the data
	u = User.objects.get(username = user)
	u.email = request.POST['email']
	u.first_name = request.POST['first_name']
	u.last_name = request.POST['last_name']
	if request.POST['admin']=='0':
		u.is_superuser = False
	else:
		u.is_superuser = True
	u.save()
	return redirect('manager:users')


def user_ch_pwd(request, user):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	if not request.user.is_superuser:
		return redirect('list:login_user')
	##change the password
	u = User.objects.get(username = user)
	if u.check_password(request.POST['old']):
		if request.POST['new']==request.POST['new_re']:
			u.set_password(request.POST['new'])
			u.save()
			return redirect('manager:users')
		return render(request, 'manager/user_ch.html', {'user':u,'err':'An error has occured'})
	return render(request, 'manager/user_ch.html', {'user':u,'err':'An error has occured'})


def groups(request):
	return HttpResponse("groups")


def group_ch(request, user):
	return HttpResponse("groups change")


def clears(request):
	os.system('rm uploads/*')
	return redirect('manager:index')

manager/templates/manager/base.html
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}AutoFor{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	{% load staticfiles %}
    <!-- favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- font awesome CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}">
    <!-- meanmenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/meanmenu/meanmenu.min.css' %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<!-- wave CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/wave/waves.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/wave/button.css' %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/scrollbar/jquery.mCustomScrollbar.min.css' %}">
    <!-- Notika icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/notika-custom-icon.css' %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- Data Table JS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
    <!-- bootstrap select CSS
        ============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-select/bootstrap-select.css' %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- Start Header Top Area -->
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo-area">
                        <a href="/"><img src="{% static 'img/logo/logo.png' %}" alt="" /></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="header-top-menu">
		                <ul class="nav navbar-nav notika-top-nav">
		                    <li class="nav-item ">
		                    	<a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
		                    		<span><i class="notika-icon notika-menus"></i></span>
		                    	</a>
		                    	<div role="menu" class="dropdown-menu message-dd">
									<div class="hd-mg-tt">
										<h2><b>Welcome {{ user.get_username }}</b></h2><hr>
									</div>
									<div class="hd-mg-va">
										{% if user.is_superuser %}
										<h2><a href="{% url 'manager:index' %}"> Admin panel</a></h2>
										{% endif %}
										<h2><a href="{% url 'list:logout_user' %}"> Log out</a></h2>
										
									</div>
								</div>
		                    </li>
		                </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Top Area -->
    <!-- Mobile Menu start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="mobile-menu">
                        <nav id="dropdown">
                            <ul class="mobile-menu-nav">
                                <li><a data-target="" href="{% url 'manager:index' %}">Dashboard</a>
                                </li>
                                <li><a data-target="" href="{% url 'manager:users' %}">Users</a>
                                </li>
                                <!--<li><a data-target="" href="">Lastest Changes</a>
                                </li>-->
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu end -->
    <!-- Main Menu area start-->
    <div class="main-menu-area mg-tb-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <ul class="nav nav-tabs notika-menu-wrap menu-it-icon-pro">
                        <li class="{% block index_active %}{% endblock %}" ><a href="{% url 'manager:index' %}"><i class="notika-icon"></i> Dashboard</a>
                        </li>
                        <li class="{% block users_active %}{% endblock %}"><a href="{% url 'manager:users' %}"><i class="notika-icon"></i> Users</a>
                        </li>
                        <!--<li class="{% block latest_active %}{% endblock %}"><a href=""><i class="notika-icon"></i> Latest Changes</a>
                        </li>-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Menu area End-->
{% block body %}
{% endblock %}

    <!-- jquery
		============================================ -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static 'js/jquery-price-slider.js' %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'js/meanmenu/jquery.meanmenu.js' %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static 'js/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/counterup/waypoints.min.js' %}"></script>
    <script src="{% static 'js/counterup/counterup-active.js' %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static 'js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <!-- sparkline JS
		============================================ -->
    <script src="{% static 'js/sparkline/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/sparkline/sparkline-active.js' %}"></script>
    <!-- flot JS
		============================================ -->
    <script src="{% static 'js/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'js/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'js/flot/flot-active.js' %}"></script>
    <!-- knob JS
		============================================ -->
    <script src="{% static 'js/knob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/knob/jquery.appear.js' %}"></script>
    <script src="{% static 'js/knob/knob-active.js' %}"></script>
    <!--  todo JS
		============================================ -->
    <script src="{% static 'js/todo/jquery.todo.js' %}"></script>
	<!--  wave JS
		============================================ -->
    <script src="{% static 'js/wave/waves.min.js' %}"></script>
    <script src="{% static 'js/wave/wave-active.js' %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Data Table JS
		============================================ -->
    <script src="{% static 'js/data-table/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/data-table/data-table-act.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'js/main.js' %}"></script>
    <!-- bootstrap select JS
        ============================================ -->
    <script src="{% static 'js/bootstrap-select/bootstrap-select.js' %}"></script>
</body>

</html>

manager/templates/manager/index.html
{% extends 'manager/base.html' %}
{% block index_active %}active{% endblock %}

{% block body %}

<div class="notika-status-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
				<div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
					<div class="website-traffic-ctn">
						<h2><span class="counter">{{ user_n }}</span></h2>
						<p>Total Users</p>
					</div>
					<div class="sparkline-bar-stats1"></div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
				<div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30 dk-res-mg-t-30">
					<div class="website-traffic-ctn">
						<h2><span class="counter">{{ case_n }}</span></h2>
						<p>Total Cases</p>
					</div>
					<div class="sparkline-bar-stats4"></div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
				<div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30 dk-res-mg-t-30">
					<div class="website-traffic-ctn">
						<h2><span class="">{{ disk_usage }}</span></h2>
						<p>Space Used</p>
					</div>
					<div class="sparkline-bar-stats4"></div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
				<div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30 dk-res-mg-t-30">
					<div class="website-traffic-ctn">
						<h2><span class="">Clear space</span></h2>
						<a href="{% url 'manager:clears' %}"><button class="btn btn-danger notika-btn-danger waves-effect">Clear</button></a>
					</div>
					<div class="sparkline-bar-stats4"></div>
				</div>
			</div>
		</div>
	</div>
</div>
<br>

<!-- Data Table area Start-->
    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
						<div class="basic-tb-hd">
                            <h2>Latest changes</h2>
                        </div>
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped table-condensed">
                                <thead>
                                    <tr>
                                        <th>User</th>
                                        <th>Action</th>
                                        <th>Object</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for log in logs %}
                                    <tr>
                                    	{% for l in log %}
		                                    <td>{{ l }}</td>
										{% endfor %}
									</tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Data Table area End-->

{% endblock %}

manager/templates/manager/user_ch.html
{% extends 'manager/base.html' %}
{% block users_active %}active{% endblock %}

{% block body %}
    <!-- Data Table area Start-->
    <div class="data-table-area">
        <div class="container">
            <div class="row">
                {% if err %}
		                    	<div class="alert alert-danger alert-mg-b-0" role="alert">{{ err }}
</div>
		                    {% endif %}
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="normal-table-list">
                        <div class="basic-tb-hd">
							<h2>General Information</h2>
						</div>
                        <div clas="bsc-tbl-cds">
		                    <table class="table table-hover table-condensed">
		                        <thead>
		                            <tr>
		                            	<th>Username</th>
		                                <th>Email Address</th>
		                                <th>First Name</th>
		                                <th>Last Name</th>
		                                <th>Admin</th>
		                                <th></th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                        	<form action="{% url 'manager:user_ch_gen' user.get_username %}" method="post">
				                        <tr>
				                        	<td>{{ user.get_username }}</td>
				                        	<td><input type="text" name="email" class="form-control" value="{{ user.email }}"></td>
				                            <td><input type="text" name="first_name" class="form-control" value="{{ user.first_name }}"></td>
				                            <td><input type="text" name="last_name" class="form-control" value="{{ user.last_name }}"></td>
				                            <td>
				                            	{% if not user.is_superuser %}
				                            		<select class="form-control" id="sel1" name="admin"><option value="0" selected>User</option><option value="1">Admin</option></select>
						                        {% else %}
						                    	    <select class="form-control" id="sel1" name="admin"><option value="0">User</option><option value="1" selected>Admin</option></select>
				                            	{% endif %}
				                            </td>
				                            <td>{% csrf_token %}<button class="btn btn-success success-icon-notika">Submit</button></a></td>
				                        </tr>
		                        	</form>
		                        </tbody>
		                    </table>
		                </div>
                    </div>
                    <br>
                    <div class="normal-table-list">
                        <div class="basic-tb-hd">
							<h2>Change Password</h2>
						</div>
                        <div clas="bsc-tbl-cds">
		                    <table class="table table-hover table-condensed">
		                        <thead>
		                            <tr>
		                            	<th>Old password</th>
		                                <th></th>
		                                <th>New password</th>
		                                <th>Confirm New password</th>
		                                <th></th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                        	<form action="{% url 'manager:user_ch_pwd' user.get_username %}" method="post">
				                        <tr>
				                        	<td><input type="password" name="old" class="form-control" value="" required></td>
				                        	<td></td>
				                        	<td><input type="password" name="new" class="form-control" value="" required></td>
				                            <td><input type="password" name="new_re" class="form-control" value="" required></td>
				                            <td>{% csrf_token %}<button class="btn btn-success success-icon-notika">Submit</button></a></td>
				                        </tr>
		                        	</form>
		                        </tbody>
		                    </table>
		                </div>
                    </div>
                    <br>
                    <div class="normal-table-list">
                        <div class="basic-tb-hd">
							<h2>Remove User</h2>
						</div>
                        <div clas="bsc-tbl-cds">
		                    <a href="{% url 'manager:user_remove' user.get_username %}"><button class="btn btn-danger danger-icon-notika">Delete</button></a>
		                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Data Table area End-->
{% endblock %}

manager/templates/manager/users.html
{% extends 'manager/base.html' %}
{% block users_active %}active{% endblock %}

{% block body %}
    <!-- Data Table area Start-->
    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="normal-table-list">
                        <div clas="bsc-tbl-cds">
		                    <table class="table table-hover table-condensed">
		                        <thead>
		                            <tr>
		                            	<th>Username</th>
		                                <th>Email Address</th>
		                                <th>First Name</th>
		                                <th>Last Name</th>
		                                <th>Last Login</th>
		                                <th></th>
		                                <th></th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            {% for user in users %}
				                        <tr>
				                        	<td>{{ user.get_username }}</td>
				                        	<td>{{ user.email }}</td>
				                            <td>{{ user.first_name }}</td>
				                            <td>{{ user.last_name }}</td>
				                            <td>{{ user.last_login }}</td>
				                            <td><a href="{% url 'manager:user_ch' user.get_username %}"><button class="btn btn-gray gray-icon-notika"><i class="notika-icon notika-menus"></i></button></a></td>
				                        </tr>
		                            {% endfor %}
		                        </tbody>
		                    </table>
		                    <br><hr>
		                    <form action="{% url 'manager:user_add' %}" method="post">
		                    <div class="cmp-tb-hd cmp-int-hd">
								<h2>New User</h2>
							</div>
							<div class="form-example-int form-horizental">
								<div class="form-group">
									<div class="row">
										<div class="col-lg-2 col-md-3 col-sm-3 col-xs-8">
											<label class="hrzn-fm">Username</label>
										</div>
										<div class="col-lg-8 col-md-7 col-sm-7 col-xs-8">
											<div class="nk-int-st">
												<input type="text" class="form-control input-sm" placeholder="Enter Username" name="username" required>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="form-example-int form-horizental">
								<div class="form-group">
									<div class="row">
										<div class="col-lg-2 col-md-3 col-sm-3 col-xs-8">
											<label class="hrzn-fm">Email Address</label>
										</div>
										<div class="col-lg-8 col-md-7 col-sm-7 col-xs-8">
											<div class="nk-int-st">
												<input type="text" class="form-control input-sm" placeholder="Enter Email" name="email">
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="form-example-int form-horizental">
								<div class="form-group">
									<div class="row">
										<div class="col-lg-2 col-md-3 col-sm-3 col-xs-8">
											<label class="hrzn-fm">First name</label>
										</div>
										<div class="col-lg-8 col-md-7 col-sm-7 col-xs-8">
											<div class="nk-int-st">
												<input type="text" class="form-control input-sm" placeholder="Enter First name" name="first_name">
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="form-example-int form-horizental">
								<div class="form-group">
									<div class="row">
										<div class="col-lg-2 col-md-3 col-sm-3 col-xs-8">
											<label class="hrzn-fm">Last name</label>
										</div>
										<div class="col-lg-8 col-md-7 col-sm-7 col-xs-8">
											<div class="nk-int-st">
												<input type="text" class="form-control input-sm" placeholder="Enter Last name" name="last_name">
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="form-example-int form-horizental mg-t-15">
								<div class="form-group">
									<div class="row">
										<div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
											<label class="hrzn-fm">Password</label>
										</div>
										<div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
											<div class="nk-int-st">
												<input type="password" class="form-control input-sm" placeholder="Password" name="password" required>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="form-example-int mg-t-15">
								<div class="row">
									<div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
									</div>
									<div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
										{% csrf_token %}<button class="btn btn-success notika-btn-success">Submit</button>
									</div>
								</div>
							</div>
		                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Data Table area End-->
{% endblock %}