autofor/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('list.urls')),
    url(r'^', include('analysis.urls')),
    url(r'^', include('disk.urls')),
    url(r'^', include('network.urls')),
    url(r'^', include('manager.urls')),
    
]+ static(settings.MEMORY_IMG_URL, document_root = settings.MEMORY_IMG_PATH) + static(settings.FILE_URL, document_root = settings.FILE_PATH)

disk/urls.py
from django.conf.urls import url
from . import views

app_name = 'disk'

urlpatterns = [
    url(r'^analysis/disk/$', views.disk, name='disk'),
    url(r'^analysis/disk/dumped/$', views.dumped_files, name='dumped_files'),
    url(r'^analysis/disk/deleted/$', views.deleted_files, name='deleted_files'),

]

list/urls.py
from django.conf.urls import url
from . import views

app_name = 'list'

urlpatterns = [
    url(r'^list$', views.list, name='list'),
    url(r'^list/ready/(?P<id>[0-9]+)/$', views.ready, name='ready'),
    url(r'^list/add$', views.add_case, name='add_case'),
    url(r'^list/delete/(?P<id>[0-9]+)/$', views.delete_case, name='delete_case'),
    url(r'^$', views.login_user, name='login_user'),
    url(r'^logout$', views.logout_user, name='logout_user'),
]

manager/urls.py
from django.conf.urls import url
from . import views

app_name = 'manager'

urlpatterns = [
    url(r'^manager/$', views.index, name='index'),
    url(r'^manager/users/$', views.users, name='users'),
    url(r'^manager/users/add$', views.user_add, name='user_add'),
    url(r'^manager/users/remove/(?P<user>[a-zA-Z]+)/$', views.user_remove, name='user_remove'),
    url(r'^manager/users/change/(?P<user>[a-zA-Z]+)/$', views.user_ch, name='user_ch'),
    url(r'^manager/users/change/gen/(?P<user>[a-zA-Z]+)/$', views.user_ch_gen, name='user_ch_gen'),
    url(r'^manager/users/change/pwd/(?P<user>[a-zA-Z]+)/$', views.user_ch_pwd, name='user_ch_pwd'),
    url(r'^manager/users/$', views.groups, name='groups'),
    url(r'^manager/groups/change/(?P<grp>[a-zA-Z]+)/$', views.group_ch, name='group_ch'),
    url(r'^manager/clears/$', views.clears, name='clears'),
]

network/urls.py
from django.conf.urls import url
from . import views

app_name = 'network'

urlpatterns = [
    url(r'^analysis/network/$', views.network, name='network'),
    url(r'^analysis/network/files/$', views.file_dumps, name='file_dumps'),
    url(r'^analysis/network/http/$', views.http_traffic, name='http_traffic'),
]

network/models.py
from django.db import models

# Create your models here.

network/views.py
from django.shortcuts import render, redirect, get_object_or_404
from list.models import Case


def network(request):
    # TEST CASES :3#
    cookie = request.COOKIES.get('CID')
    if not cookie:
        return render(request, 'analysis/404.html')
    case = get_object_or_404(Case, c_fingerprint=cookie)
    if not request.user.is_authenticated:
        return redirect('list:login_user')
    if not case.c_owner == request.user:
        return render(request, 'analysis/404.html')
    # end test cases#
    # capinfos
    list_data = open('network/templates/network/' + case.c_owner.username + '_' + case.c_name + '_' + 'capinfos.txt').read()
    lines = list_data.splitlines()
    l = []
    l.append([lines[5].split(':')[1], lines[6].split(':')[1], lines[9].split(':',1)[1], lines[10].split(':',1)[1], lines[11].split(':')[1]])
    return render(request, 'network_index.html', {'case': case, 'list': l[0]})


def file_dumps(request):
    # TEST CASES :3#
    cookie = request.COOKIES.get('CID')
    if not cookie:
        return render(request, 'analysis/404.html')
    case = get_object_or_404(Case, c_fingerprint=cookie)
    if not request.user.is_authenticated:
        return redirect('list:login_user')
    if not case.c_owner == request.user:
        return render(request, 'analysis/404.html')
    # end test cases#
    list_data = open('network/templates/network/' + case.c_owner.username + '_' + case.c_name + '_' + 'tcpxtract.txt').read()
    lines = list_data.splitlines()
    list = []
    for line in lines:
        list.append([line.split('files/')[1],line.split(',')[0]])
    return render(request, 'file_dump.html', {'files':list})


def http_traffic(request):
    # TEST CASES :3#
    cookie = request.COOKIES.get('CID')
    if not cookie:
        return render(request, 'analysis/404.html')
    case = get_object_or_404(Case, c_fingerprint=cookie)
    if not request.user.is_authenticated:
        return redirect('list:login_user')
    if not case.c_owner == request.user:
        return render(request, 'analysis/404.html')
    # end test cases#
    name = 'network/' + case.c_owner.username + '_' + case.c_name + '_' + 'captipper.html'
    return render(request, 'http_traffic.html', {'name':name})

network/templates/base_net.html
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="ISO-8859-1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}AutoFor{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	{% load staticfiles %}
    <!-- favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- font awesome CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}">
    <!-- meanmenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/meanmenu/meanmenu.min.css' %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<!-- wave CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/wave/waves.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/wave/button.css' %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/scrollbar/jquery.mCustomScrollbar.min.css' %}">
    <!-- Notika icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/notika-custom-icon.css' %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- Data Table JS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
    <!-- bootstrap select CSS
        ============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-select/bootstrap-select.css' %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- Start Header Top Area -->
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo-area">
                        <a href="/"><img src="{% static 'img/logo/logo.png' %}" alt="" /></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="header-top-menu">
		                <ul class="nav navbar-nav notika-top-nav">
		                    <li class="nav-item ">
		                    	<a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
		                    		<span><i class="notika-icon notika-menus"></i></span>
		                    	</a>
		                    	<div role="menu" class="dropdown-menu message-dd">
									<div class="hd-mg-tt">
										<h2><b>Welcome {{ user.get_username }}</b></h2><hr>
									</div>
									<div class="hd-mg-va">
										{% if user.is_superuser %}
										<h2><a href="{% url 'manager:index' %}"> Admin panel</a></h2>
										{% endif %}
										<h2><a href="{% url 'list:logout_user' %}"> Log out</a></h2>
										
									</div>
								</div>
		                    </li>
		                </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Top Area -->
    <!-- Mobile Menu start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="mobile-menu">
                        <nav id="dropdown">
                            <ul class="mobile-menu-nav">
                                <li><a data-toggle="collapse" data-target="" href="#">Pcap info</a>
                                    <ul class="collapse dropdown-header-top">
                                        <li><a href="{% url 'network:network' %}">Basic info</a></li>
                                    </ul>
                                </li>
                                <li><a data-toggle="collapse" data-target="" href="#">Connections</a>
                                    <ul class="collapse dropdown-header-top">
                                        <li><a href="">summary</a></li>
                                    </ul>
                                </li>
                                <li><a data-toggle="collapse" data-target="" href="#">Files</a>
                                    <ul class="collapse dropdown-header-top">
                                        <li><a href="{% url 'network:file_dumps' %}">dumped files</a></li>
                                    </ul>
                                </li>
                                <li><a data-toggle="collapse" data-target="" href="#">Malicious Traffic</a>
                                    <ul class="collapse dropdown-header-top">
                                        <li><a href="{% url 'network:http_traffic' %}">HTTP</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu end -->
    <!-- Main Menu area start-->
    <div class="main-menu-area mg-tb-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <ul class="nav nav-tabs notika-menu-wrap menu-it-icon-pro">
                        <li class="{% block info_active %}{% endblock %}"><a data-toggle="tab" href="#info"><i class="notika-icon"></i> Pcap info</a>
                        </li>
                        <li class="{% block conn_active %}{% endblock %}"><a data-toggle="tab" href="#conn"><i class="notika-icon"></i> Connections</a>
                        </li>
                        <li class="{% block files_active %}{% endblock %}"><a data-toggle="tab" href="#files"><i class="notika-icon"></i> Files</a>
                        </li>
                        <li class="{% block maltraffic_active %}{% endblock %}"><a data-toggle="tab" href="#maltraffic"><i class="notika-icon"></i> Malicious Traffic</a>
                        </li>
                    </ul>
                    <div class="tab-content custom-menu-content">
                        <div id="info" class="tab-pane {% block info__active %}{% endblock %} notika-tab-menu-bg">
                            <ul class="notika-main-menu-dropdown">
                                <li class=""><a href="{% url 'network:network' %}">Basic info</a>
                                </li>
                            </ul>
                        </div>
                        <div id="conn" class="tab-pane {% block conn__active %}{% endblock %} notika-tab-menu-bg">
                            <ul class="notika-main-menu-dropdown">
                                <li class=""><a href="">Summary</a>
                                </li>
                            </ul>
                        </div>
                        <div id="files" class="tab-pane {% block files__active %}{% endblock %} notika-tab-menu-bg">
                            <ul class="notika-main-menu-dropdown">
                                <li class=""><a href="{% url 'network:file_dumps' %}">Dumped files</a>
                                </li>
                            </ul>
                        </div>
                        <div id="maltraffic" class="tab-pane {% block maltraffic__active %}{% endblock %} notika-tab-menu-bg">
                            <ul class="notika-main-menu-dropdown">
                                <li class=""><a href="{% url 'network:http_traffic' %}">HTTP</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Menu area End-->
{% block body %}
{% endblock %}

    <!-- jquery
		============================================ -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static 'js/jquery-price-slider.js' %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'js/meanmenu/jquery.meanmenu.js' %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static 'js/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/counterup/waypoints.min.js' %}"></script>
    <script src="{% static 'js/counterup/counterup-active.js' %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static 'js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <!-- sparkline JS
		============================================ -->
    <script src="{% static 'js/sparkline/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/sparkline/sparkline-active.js' %}"></script>
    <!-- flot JS
		============================================ -->
    <script src="{% static 'js/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'js/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'js/flot/flot-active.js' %}"></script>
    <!-- knob JS
		============================================ -->
    <script src="{% static 'js/knob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/knob/jquery.appear.js' %}"></script>
    <script src="{% static 'js/knob/knob-active.js' %}"></script>
    <!--  todo JS
		============================================ -->
    <script src="{% static 'js/todo/jquery.todo.js' %}"></script>
	<!--  wave JS
		============================================ -->
    <script src="{% static 'js/wave/waves.min.js' %}"></script>
    <script src="{% static 'js/wave/wave-active.js' %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Data Table JS
		============================================ -->
    <script src="{% static 'js/data-table/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/data-table/data-table-act.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'js/main.js' %}"></script>
    <!-- bootstrap select JS
        ============================================ -->
    <script src="{% static 'js/bootstrap-select/bootstrap-select.js' %}"></script>
</body>

</html>

network/templates/file_dump.html
{% extends 'base_net.html' %}
{% block files_active %}active{% endblock %}
{% block files__active %}active{% endblock %}

{% block body %}


    <!-- Data Table area Start-->
    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>File</th>
                                        <th>Output</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for file in files %}
                                    <tr>
		                                	{% for column in file %}
		                                    <td>{{ column }}</td>
		                                    {% endfor %}
		                                <td><a href="/files/{{file.0}}" target="_blank"><button class="btn btn-success notika-btn-success waves-effect">Download</button></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Data Table area End-->
{% endblock %}

network/templates/http_traffic.html
{% extends 'base_net.html' %}
{% block maltraffic_active %}active{% endblock %}
{% block maltraffic__active %}active{% endblock %}

{% block body %}


{% include name %}

{% endblock %}

network/templates/network_index.html
{% extends 'base_net.html' %}
{% block info_active %}active{% endblock %}
{% block info__active %}active{% endblock %}

{% block body %}

<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>Case: {{ case.c_name }}</h2>
										<h4>Type: {{ case.c_type }}</h4>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

    <div class="notika-status-area">
        <div class="container">
            <div class="row ">
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
                        <div class="website-traffic-ctn">
                            <h2><span class="">{{ list.1 }}</span></h2>
                            <p>File size</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
                        <div class="website-traffic-ctn">
                            <h2><span class="">{{ list.0 }}</span></h2>
                            <p>Number of packets</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
                        <div class="website-traffic-ctn">
                            <h2><span class="">{{ list.2 }}</span></h2>
                            <p>Data byte rate</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
                        <div class="website-traffic-ctn">
                            <h2><span class="">{{ list.3 }}</span></h2>
                            <p>First packet time</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
                        <div class="website-traffic-ctn">
                            <h2><span class="">{{ list.4 }}</span></h2>
                            <p>Last packet time</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}