autofor/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('list.urls')),
    url(r'^', include('analysis.urls')),
    url(r'^', include('disk.urls')),
    url(r'^', include('network.urls')),
    url(r'^', include('manager.urls')),
    
]+ static(settings.MEMORY_IMG_URL, document_root = settings.MEMORY_IMG_PATH) + static(settings.FILE_URL, document_root = settings.FILE_PATH)

disk/urls.py
from django.conf.urls import url
from . import views

app_name = 'disk'

urlpatterns = [
    url(r'^analysis/disk/$', views.disk, name='disk'),
    url(r'^analysis/disk/dumped/$', views.dumped_files, name='dumped_files'),
    url(r'^analysis/disk/deleted/$', views.deleted_files, name='deleted_files'),

]

list/urls.py
from django.conf.urls import url
from . import views

app_name = 'list'

urlpatterns = [
    url(r'^list$', views.list, name='list'),
    url(r'^list/ready/(?P<id>[0-9]+)/$', views.ready, name='ready'),
    url(r'^list/add$', views.add_case, name='add_case'),
    url(r'^list/delete/(?P<id>[0-9]+)/$', views.delete_case, name='delete_case'),
    url(r'^$', views.login_user, name='login_user'),
    url(r'^logout$', views.logout_user, name='logout_user'),
]

manager/urls.py
from django.conf.urls import url
from . import views

app_name = 'manager'

urlpatterns = [
    url(r'^manager/$', views.index, name='index'),
    url(r'^manager/users/$', views.users, name='users'),
    url(r'^manager/users/add$', views.user_add, name='user_add'),
    url(r'^manager/users/remove/(?P<user>[a-zA-Z]+)/$', views.user_remove, name='user_remove'),
    url(r'^manager/users/change/(?P<user>[a-zA-Z]+)/$', views.user_ch, name='user_ch'),
    url(r'^manager/users/change/gen/(?P<user>[a-zA-Z]+)/$', views.user_ch_gen, name='user_ch_gen'),
    url(r'^manager/users/change/pwd/(?P<user>[a-zA-Z]+)/$', views.user_ch_pwd, name='user_ch_pwd'),
    url(r'^manager/users/$', views.groups, name='groups'),
    url(r'^manager/groups/change/(?P<grp>[a-zA-Z]+)/$', views.group_ch, name='group_ch'),
    url(r'^manager/clears/$', views.clears, name='clears'),
]

list/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from datetime import datetime

class Case(models.Model):
    type_choices = (
    	('memory', 'memory'),
    	('disk', 'disk'),
    	('network', 'network'),
    )

   # c_id = models.IntegerField(primary_key=True)
    c_name = models.CharField(max_length=250, unique=True, default='')
    c_type = models.CharField(
    	max_length=250,
    	choices=type_choices,
    	default='memory',
    )
    c_date_created = models.DateTimeField(default=datetime.now, blank=True)
    c_status = models.BooleanField(default=False)
    c_file = models.FileField(upload_to='uploads/')
    c_fingerprint = models.CharField(max_length=250, default='', unique=True)
    c_owner = models.ForeignKey(User, on_delete='')
    c_unsupported = models.BooleanField(default=False)

    def __str__(self):
        return self.c_name

list/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from .models import Case
from analysis.script import analyse
from disk.script import disk_analyse
from network.script import network_analyse
import hashlib
from functools import partial
import os


def list(request):
	print (request)
	if not request.user.is_authenticated:
		return render(request, 'list/login.html')
	else:
		cases = Case.objects.filter(c_owner=request.user)
		return render(request, 'list/index.html', {'cases':cases})


def ready(request, id):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	else:
		case = Case.objects.get(pk=id)
		url = ''
		if not case.c_owner == request.user:
			url = 'analysis:err'
		elif case.c_type == 'memory':
			url = 'analysis:memory'
		elif case.c_type == 'disk':
			url = 'disk:disk'
		elif case.c_type == 'network':
			url = 'network:network'
		else:
			url = 'analysis:err'
		response = redirect(url)
		response.set_cookie('CID', case.c_fingerprint, max_age=900)
		return response


def add_case(request):
	if not request.user.is_authenticated:
		return redirect('list:login_user')
	else:
		if request.method == 'POST':
			c_name = request.POST['name'].replace(" ", "_")
			c_type = request.POST['type']
			c_owner = request.user
			##changing filename
			uploaded_file = request.FILES['file']
			fs = FileSystemStorage()
			f = fs.save('uploads/'+c_owner.username+'_'+c_name, uploaded_file)
			c_file = fs.url(f)
			##fingerprint
			with open(c_file, mode='rb') as f:
				d = hashlib.md5()
				for buf in iter(partial(f.read, 128), b''):
					d.update(buf)
			c_fingerprint = d.hexdigest()
			
			case = Case(c_name=c_name, c_type=c_type, c_file=c_file, c_fingerprint=c_fingerprint, c_owner=c_owner)
			case.save()

			if case.c_type == 'memory':
				#get selected plugins to run
				#selected_plugs=['envars', 'pslist', 'netscan', 'filescan', 'iehistory', 'chromehistory', 'firefoxhistory', 'cmdscan','screenshot', 'malfind', 'hashdump']
				#script calling
				analyse(c_name, c_type, c_file, c_owner.username)
				#//end//#
			elif case.c_type == 'disk':
				disk_analyse(c_name, c_type, c_file, c_owner.username)
			elif case.c_type == 'network':
				network_analyse(c_name, c_type, c_file, c_owner.username)

		return redirect('list:list')


def delete_case(request, id):
	if not request.user.is_authenticated:
		return render(request, 'list/login.html')
	else:
		case = Case.objects.get(pk=id)
		if case.c_owner == request.user:
			os.popen('rm ' + str(case.c_file))
			case.delete()
		return redirect('list:list')


def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				cases = Case.objects.filter(c_owner=request.user)
				return render(request, 'list/index.html', {'cases':cases})
			else:
				return redirect('list:login_user')
		else:
			return redirect('list:login_user')
	else:
		if request.user.is_authenticated:
			cases = Case.objects.filter(c_owner=request.user)
			return render(request, 'list/index.html', {'cases':cases})
		else:
			return render(request, 'list/login.html')


def logout_user(request):
	logout(request)
	return redirect('list:login_user')

list/templates/list/base_in.html
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}AutoFor{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	{% load staticfiles %}
    <!-- favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- font awesome CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}">
    <!-- meanmenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/meanmenu/meanmenu.min.css' %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<!-- wave CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/wave/waves.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/wave/button.css' %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/scrollbar/jquery.mCustomScrollbar.min.css' %}">
    <!-- Notika icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/notika-custom-icon.css' %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- bootstrap select CSS
        ============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-select/bootstrap-select.css' %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- Start Header Top Area -->
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo-area">
                        <a href="/"><img src="{% static 'img/logo/logo.png' %}" alt="" /></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="header-top-menu">
		                <ul class="nav navbar-nav notika-top-nav">
		                    <li class="nav-item ">
		                    	<a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
		                    		<span><i class="notika-icon notika-menus"></i></span>
		                    	</a>
		                    	<div role="menu" class="dropdown-menu message-dd">
									<div class="hd-mg-tt">
										<h2><b>Welcome {{ user.get_username }}</b></h2><hr>
									</div>
									<div class="hd-mg-va">
										{% if user.is_superuser %}
										<h2><a href="{% url 'manager:index' %}"> Admin panel</a></h2>
										{% endif %}
										<h2><a href="{% url 'list:logout_user' %}"> Log out</a></h2>
										
									</div>
								</div>
		                    </li>
		                </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Top Area -->
{% block body %}
{% endblock %}

    <!-- jquery
		============================================ -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static 'js/jquery-price-slider.js' %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'js/meanmenu/jquery.meanmenu.js' %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static 'js/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/counterup/waypoints.min.js' %}"></script>
    <script src="{% static 'js/counterup/counterup-active.js' %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static 'js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <!-- sparkline JS
		============================================ -->
    <script src="{% static 'js/sparkline/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/sparkline/sparkline-active.js' %}"></script>
    <!-- flot JS
		============================================ -->
    <script src="{% static 'js/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'js/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'js/flot/flot-active.js' %}"></script>
    <!-- knob JS
		============================================ -->
    <script src="{% static 'js/knob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/knob/jquery.appear.js' %}"></script>
    <script src="{% static 'js/knob/knob-active.js' %}"></script>
    <!--  todo JS
		============================================ -->
    <script src="{% static 'js/todo/jquery.todo.js' %}"></script>
	<!--  wave JS
		============================================ -->
    <script src="{% static 'js/wave/waves.min.js' %}"></script>
    <script src="{% static 'js/wave/wave-active.js' %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'js/main.js' %}"></script>
    <!-- bootstrap select JS
        ============================================ -->
    <script src="{% static 'js/bootstrap-select/bootstrap-select.js' %}"></script>
</body>

</html>

list/templates/list/index.html
{% extends 'list/base_in.html' %}

{% block body %}
	<!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>Case</h2>
										<p>Make a new case or choose an existant one</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->
    <!-- Case area Start-->
    <div class="normal-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="normal-table-list mg-t-30">
                        <div class="basic-tb-hd">
                            <h2>Select a case</h2>
                        </div>
                        <div class="bsc-tbl-st">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Type</th>
                                        <th>Date created</th>
                                        <th>Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if cases %}
                            		{% for case in cases %}
		                                <tr>
		                                    <td>{{ case.c_name }}</td>
		                                    <td>{{ case.c_type }}</td>
		                                    <td>{{ case.c_date_created }}</td>
		                                    {% if case.c_unsupported %}
		                                    		<td><a><button class="btn btn-danger notika-btn-danger" disabled>Unsupported</button></td>
		                                    {% elif case.c_status %}
		 		                            		<td><a href="{% url 'list:ready' case.id %}"><button class="btn btn-success notika-btn-success waves-effect">Ready</button></a></td>
		 		                            {% else %}
		 		                            		<td><button class="btn btn-success notika-btn-success waves-effect" disabled>Pending</button></td>
		                                    {% endif %}
		                                    <td><a href="{% url 'list:delete_case' case.id %}"><button class="btn btn-danger notika-btn-danger waves-effect">Delete</button></a></td>
		                                </tr>
		                        	{% endfor %}
		                        {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <!-- New Case area Start-->
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-example-wrap mg-t-30">
                      <form action="{% url 'list:add_case' %}" name="case_f" method="post" enctype="multipart/form-data">
                      	{% csrf_token %}
                        <div class="cmp-tb-hd cmp-int-hd">
                            <h2>New Case</h2>
                        </div>
                        <div class="form-example-int form-horizental">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                                        <label class="hrzn-fm">Case Name</label>
                                    </div>
                                    <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                        <div class="nk-int-st">
                                            <input name="name" type="text" class="form-control input-sm" placeholder="Enter a Name">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                                        <label class="hrzn-fm">Type</label>
                                    </div>
                                    <div class="col-lg-3 bootstrap-select fm-cmp-mg">
                                        <select name="type" class="selectpicker" required>
                                            <option value="memory">Memory forensics</option>
                                            <option value="disk">Disk forensics</option>
                                            <option value="network">Network forensics</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                                        <label class="hrzn-fm">Choose a file</label>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="custom-file">
										    <input name="file" type="file" class="custom-file-input" id="validatedCustomFile" required>
										    <label class="custom-file-label" for="validatedCustomFile"></label>
										</div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                                </div>
                                <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                                    <button class="btn btn-success notika-btn-success">Create</button>
                                </div>
                            </div>
                        </div>
                      </form>
                    </div>
                </div>
            </div>
            <!-- New Case area End-->
        </div>
    </div>
    <!-- Case area End-->

{% endblock %}

list/templates/list/login.html
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}AutoFor{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	{% load staticfiles %}
    <!-- favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- font awesome CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<!-- wave CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/wave/waves.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/wave/button.css' %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/scrollbar/jquery.mCustomScrollbar.min.css' %}">
    <!-- Notika icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/notika-custom-icon.css' %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- bootstrap select CSS
        ============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-select/bootstrap-select.css' %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- Login Register area Start-->
    <form action="{% url 'list:login_user' %}" method="post" name="login_f">
    <div class="login-content">
        <!-- Login -->
        {% csrf_token %}
        <div class="nk-block toggled" id="l-login">
            <div class="nk-form">
                <div class="input-group">
                    <span class="input-group-addon nk-ic-st-pro"><i class="notika-icon notika-support"></i></span>
                    <div class="nk-int-st">
                        <input name="username" type="text" class="form-control" placeholder="Username" required autofocus>
                    </div>
                </div>
                <div class="input-group mg-t-15">
                    <span class="input-group-addon nk-ic-st-pro"><i class="notika-icon notika-edit"></i></span>
                    <div class="nk-int-st">
                        <input name="password" type="password" class="form-control" placeholder="Password" required>
                    </div>
                </div><br>
                <div class="">
                	<button class="btn btn-success btn-lg" type="submit">Login</button>
                </div>
            </div>
            
        </div>
        </form>
    <!-- Login Register area End-->
    <!-- jquery
		============================================ -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static 'js/jquery-price-slider.js' %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'js/meanmenu/jquery.meanmenu.js' %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static 'js/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/counterup/waypoints.min.js' %}"></script>
    <script src="{% static 'js/counterup/counterup-active.js' %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static 'js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <!-- sparkline JS
		============================================ -->
    <script src="{% static 'js/sparkline/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/sparkline/sparkline-active.js' %}"></script>
    <!-- flot JS
		============================================ -->
    <script src="{% static 'js/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'js/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'js/flot/flot-active.js' %}"></script>
    <!-- knob JS
		============================================ -->
    <script src="{% static 'js/knob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/knob/jquery.appear.js' %}"></script>
    <script src="{% static 'js/knob/knob-active.js' %}"></script>
    <!--  Chat JS
		============================================
    <script src="{% static 'js/chat/jquery.chat.js' %}"></script> -->
    <!--  todo JS
		============================================ -->
    <script src="{% static 'js/todo/jquery.todo.js' %}"></script>
	<!--  wave JS
		============================================ -->
    <script src="{% static 'js/wave/waves.min.js' %}"></script>
    <script src="{% static 'js/wave/wave-active.js' %}"></script>
    <!-- icheck JS
		============================================ -->
    <script src="{% static 'js/icheck/icheck.min.js' %}"></script>
    <script src="{% static 'js/icheck/icheck-active.js' %}"></script>
    <!--  todo JS
		============================================ -->
    <script src="{% static 'js/todo/jquery.todo.js' %}"></script>
    <!-- Login JS
		============================================ -->
    <script src="{% static 'js/login/login-action.js' %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>